# Generated by Django 5.1.6 on 2025-02-27 11:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="UID пользователя",
            ),
        ),
    ]
