# Generated by Django 5.1.6 on 2025-02-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallets", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="wallet",
            old_name="uuid",
            new_name="wallet_uuid",
        ),
    ]
